# Generated by Django 4.1.3 on 2022-12-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.request'),
        ),
        migrations.AddField(
            model_name='request',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
