# Generated by Django 4.1.3 on 2022-12-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="day_availability",
            field=models.IntegerField(blank=True),
        ),
    ]
