# Generated by Django 4.1.3 on 2022-11-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="request", name="student_availability",),
        migrations.AddField(
            model_name="request",
            name="day_availability",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="request",
            name="lesson_interval",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="request",
            name="time_availability",
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user", name="username", field=models.CharField(max_length=50),
        ),
    ]
