# Generated by Django 4.1.3 on 2022-11-29 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="lesson", name="instrument",),
        migrations.AlterField(
            model_name="request",
            name="time_availability",
            field=models.TimeField(
                default=datetime.time(17, 53, 19, 156825), null=True
            ),
        ),
    ]
