# Generated by Django 4.1.3 on 2022-11-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_remove_request_student_availability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="time_availability",
            field=models.TimeField(null=True),
        ),
    ]
