# Generated by Django 4.1.3 on 2022-11-29 17:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_remove_lesson_instrument_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="instrument",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessons.instrument",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="request",
            name="time_availability",
            field=models.TimeField(
                default=datetime.time(17, 53, 37, 125112), null=True
            ),
        ),
    ]
