# Generated by Django 4.1.3 on 2022-12-02 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_remove_request_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="student",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessons.student",
            ),
        ),
    ]
