# Generated by Django 4.1.3 on 2022-12-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_lesson_request_request_paid"),
    ]

    operations = [
        migrations.AlterModelOptions(name="lesson", options={"ordering": ["-id"]},),
        migrations.AlterModelOptions(name="request", options={"ordering": ("-id",)},),
    ]
