# Generated by Django 4.1.3 on 2022-12-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_alter_lesson_options_alter_request_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="lesson", options={"ordering": ["date"]},),
        migrations.AlterModelOptions(name="user", options={"ordering": ("id",)},),
    ]
