# Generated by Django 4.1.3 on 2022-11-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_student_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="type",),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="User", max_length=50),
        ),
    ]
