# Generated by Django 4.1.3 on 2022-12-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_alter_request_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="base_price",
            field=models.IntegerField(default=0),
        ),
    ]
