# Generated by Django 4.1.3 on 2022-11-24 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lessons.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_student_type_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('lessons.user',),
            managers=[
                ('objects', lessons.models.UserManager()),
            ],
        ),
    ]
