# Generated by Django 4.1.3 on 2022-12-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0005_alter_instrument_base_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
            ],
        ),
    ]
