# Generated by Django 4.1.3 on 2022-11-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_alter_request_time_availability"),
        ("lessons", "0005_director"),
    ]

    operations = []
