# Generated by Django 4.1.3 on 2022-11-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0005_lesson_day_alter_lesson_time"),
    ]

    operations = [
        migrations.AlterModelOptions(name="lesson", options={"ordering": ("-date",)},),
        migrations.RemoveField(model_name="lesson", name="day",),
        migrations.RemoveField(model_name="lesson", name="time",),
        migrations.AddField(
            model_name="lesson", name="date", field=models.DateTimeField(null=True),
        ),
    ]
