# Generated by Django 4.1.3 on 2022-12-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_term"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="term", options={"ordering": ("start_date",)},
        ),
        migrations.AlterField(
            model_name="term", name="end_date", field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="term", name="start_date", field=models.DateField(null=True),
        ),
    ]
