# Generated by Django 4.1.3 on 2022-11-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_merge_20221126_1824"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument", name="name", field=models.CharField(max_length=30),
        ),
    ]
