# Generated by Django 4.1.3 on 2022-12-06 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_term_options_request_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.request'),
        ),
    ]
