# Generated by Django 4.1.3 on 2022-12-06 20:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_alter_term_options_alter_term_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="term",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessons.term",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="request",
            name="lesson_count",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(3),
                    django.core.validators.MaxValueValidator(20),
                ]
            ),
        ),
    ]
