# Generated by Django 4.1.3 on 2022-12-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0008_request_term_alter_request_lesson_count"),
    ]

    operations = [
        migrations.RemoveField(model_name="request", name="term",),
    ]
